#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged


# feat: Uma nova funcionalidade.
# fix: Uma correção de bug.
# docs: Mudanças na documentação.
# style: Mudanças que não afetam o significado do código (espaços em branco, formatação, ponto e vírgula faltando, etc.).
# refactor: Uma mudança de código que nem corrige um bug nem adiciona uma funcionalidade.
# perf: Uma mudança de código que melhora o desempenho.
# test: Adicionando testes faltantes ou corrigindo testes existentes.
# build: Mudanças que afetam o sistema de build ou dependências externas (escopos de exemplo: gulp, broccoli, npm).
# ci: Mudanças em arquivos e scripts de configuração de CI (exemplos de escopo: Travis, Circle, BrowserStack, SauceLabs).
# chore: Outras mudanças que não modificam arquivos de código ou testes.
# revert: Revertendo um commit anterior.


